# -*- coding: utf-8 -*-
"""Палій_DA6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pi35smm9mOZmHMKpfOxh_oot1Xu6g-9Z
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans
import streamlit as st

df = pd.read_csv('spotify_global_trends.csv')

st.set_page_config(
    page_title="Топ-200 Spotify",
    page_icon="🎶",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        'Get Help': 'https://docs.streamlit.io/',
        'Report a bug': 'https://github.com/streamlit/streamlit/issues',
        'About': 'Інтерактивна панель для топ-200 пісень за прослуховуваннями'
    }
)

st.sidebar.title("Панель фільтрації")

selected_artist_name = st.sidebar.multiselect("Виконавець", df["artist_name"].unique(), default=df["artist_name"].unique()[:5])
selected_genre = st.sidebar.multiselect("Жанр", df["genre"].unique(), default=df["genre"].unique())
selected_country = st.sidebar.multiselect("Країна", df["country"].unique(), default=df["country"].unique())
selected_longevity = st.sidebar.radio("Завантаження треку", df["longevity"].unique())

selected_max_streams = st.sidebar.slider(
    "Прослуховування",
    min_value=int(df["streams"].min()),
    max_value=int(df["streams"].max()),
    value=int(df["streams"].max()),
    step=1000
)

df_filtered = df[
    (df["artist_name"] == selected_artist_name) &
    (df["genre"].isin(selected_genre)) &
    (df["country"].isin(selected_country)) &
    (df["longevity"] == selected_longevity) &
    (df["streams"] <= selected_max_streams)
]

st.sidebar.markdown("Побудова регресії")
numeric_columns = df_filtered.select_dtypes(include=np.number).columns.tolist()

reg_x = st.sidebar.selectbox("Оберіть змінну X", numeric_columns, index=0)
reg_y = st.sidebar.selectbox("Оберіть змінну Y", numeric_columns, index=1)
show_regression = st.sidebar.checkbox("Показати регресійну модель")

chart_option = st.sidebar.radio(
    "📈 Оберіть графік для перегляду:",
    [
        "Дні vs Прослуховування",
        "Boxplot прослуховувань по жанрам",
        "Пісень за прослуховуваннями",
        "Кластеризація виконавців"
    ]
)

st.title("🎶 Дашборд Топ-200 Spotify")
st.subheader(f"🔍 Відфільтровано {df_filtered.shape[0]}")

csv = df_filtered.to_csv(index=False).encode("utf-8")
st.download_button(
    label="⬇️ Завантажити CSV",
    data=csv,
    file_name="filtered.csv",
    mime="text/csv"
)

st.subheader("Оберіть, які стовпці таблиці відображати")

all_columns = df_filtered.columns.tolist()
default_columns = ["track_name", "genre", "country", "streams", "pos"]

selected_columns = st.multiselect(
    "Оберіть стовпці для перегляду",
    options=all_columns,
    default=[col for col in default_columns if col in all_columns]
)

if selected_columns:
    st.dataframe(df_filtered[selected_columns])
else:
    st.info("Оберіть хоча б один стовпець, щоб побачити таблицю.")

if chart_option == "Дні vs Прослуховування":
    st.subheader("Дні vs Прослуховування")
    chart = alt.Chart(df_filtered).mark_circle(size=100).encode(
        x="days:Q",
        y="streams:Q",
        color="artist_name:N",
        tooltip=["track_name", "days", "streams", "artist_name"]
    ).interactive().properties(title="Дні vs Прослуховування")
    st.altair_chart(chart, width='stretch')

elif chart_option == "Boxplot прослуховувань по жанрам":
    st.subheader("Boxplot прослуховувань по жанрам")
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.boxplot(data=df_filtered, x="genre", y="streams", ax=ax)
    ax.set_title("Прослуховування за жанрами")
    st.pyplot(fig)

elif chart_option == "Пісень за прослуховуваннями":
    st.subheader("Пісень за прослуховуваннями")
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.barplot(
        data=df_filtered,
        x="streams",
        y="track_name",
        estimator="mean",
        ax=ax
    )
    ax.set_title("Пісень за прослуховуваннями")
    st.pyplot(fig)

elif chart_option == "Кластеризація виконавців":
    st.subheader("Кластеризація виконавців")
    cluster_data = df_filtered[["streams", "days"]].dropna().copy()

    if cluster_data.shape[0] >= 3:
        kmeans = KMeans(n_clusters=3, random_state=0)
        cluster_data["Cluster"] = kmeans.fit_predict(cluster_data)

        chart = alt.Chart(cluster_data).mark_circle(size=60).encode(
            x="days:Q",
            y="streams:Q",
            color="Cluster:N",
            tooltip=["days", "streams", "Cluster"]
        ).interactive().properties(title="Кластеризація за тривалістю в топі та прослуховуваннями")
        st.altair_chart(chart, width='stretch')
    else:
        st.warning("Недостатньо даних для кластеризації (потрібно ≥ 3 рядки).")

if show_regression:
    st.subheader(f"📈 Лінійна регресія: {reg_y} ~ {reg_x}")

    df_reg = df_filtered[[reg_x, reg_y]].dropna()

    if df_reg.shape[0] >= 2:
        model = LinearRegression()
        model.fit(df_reg[[reg_x]], df_reg[reg_y])
        y_pred = model.predict(df_reg[[reg_x]])

        coef = model.coef_[0]
        intercept = model.intercept_
        r2 = model.score(df_reg[[reg_x]], df_reg[reg_y])

        st.markdown(f"**Коефіцієнт нахилу (β):** {coef:.4f}")
        st.markdown(f"**Зсув (intercept):** {intercept:.4f}")
        st.markdown(f"**R²:** {r2:.4f}")

        fig, ax = plt.subplots(figsize=(8, 5))
        sns.scatterplot(data=df_reg, x=reg_x, y=reg_y, ax=ax)
        sns.lineplot(x=df_reg[reg_x], y=y_pred, color='red', ax=ax)
        ax.set_title(f"Регресія {reg_y} ~ {reg_x}")
        st.pyplot(fig)
    else:
        st.warning("Недостатньо даних для побудови регресії.")
